name: C++ Build and Test

on:
  push:
    branches: [ main ]
    tags: 
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          doxygen \
          libboost-all-dev \
          nlohmann-json3-dev

    - name: Doxygen action
      uses: mattnotmitt/doxygen-action@v1.1.0
      with:
          doxyfile-path: ./Doxyfile
          working-directory: .

    - name: Configure CMake
      run: cmake -B build -S .

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Run tests
      run: ctest --test-dir build --output-on-failure

    - name: Create Release
      uses: softprops/action-gh-release@v2
      if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
      with:
        files: |
          Broker
          BrokerClient
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: GH Pages Deployment
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./doc/html/
        enable_jekyll: false
        allow_empty_commit: false
        force_orphan: true
        publish_branch: gh-pages